version: '2'
services:
  nacos-gateway:
    build:
      context: ./
    restart: always
    ports:
      - 9998:9998
    container_name: nacos-providerB-by-docker-compose-build
    hostname: nacos-providerB-by-docker-compose-build
    image: nacos-providerB-by-docker-compose-build